export const tiposError = [
  "valueMissing",
  "typeMismatch",
  "patternMismatch",
  "rangeOverflow",
  "rangeUnderflow",
  "stepMismatch",
  "tooLong",
  "tooShort",
  "url",
  "email",
  "numericality",
  "customError",
];

export const mensajes = {
  nombre: {
    valueMissing: "El campo nombre no puede estar vacío.",
    typeMismatch: "Por favor, ingrese un nombre válido.",
    patternMismatch: "Por favor, ingrese un nombre válido.",
    rangeOverflow: "El valor es demasiado grande.",
    rangeUnderflow: "El valor es demasiado pequeño.",
    stepMismatch: "El valor no está en el paso correcto.",
    tooLong: "El nombre es demasiado largo.",
    tooShort: "Por favor, ingrese un nombre válido.",
    url: "El campo nombre no debe ser una URL.",
    email: "El campo nombre no debe ser un correo electrónico.",
    numericality: "El campo nombre no debe ser numérico.",
    customError: "El nombre ingresado no es válido.",
  },
  email: {
    valueMissing: "El campo email no puede estar vacío.",
    typeMismatch: "Por favor, ingrese un email válido.",
    patternMismatch: "Por favor, ingrese un email válido.",
    rangeOverflow: "El valor es demasiado grande.",
    rangeUnderflow: "El valor es demasiado pequeño.",
    stepMismatch: "El valor no está en el paso correcto.",
    tooLong: "El email es demasiado largo.",
    tooShort: "Por favor, ingrese un e-mail válido.",
    url: "El campo email no debe ser una URL.",
    email: "Por favor, ingrese un email válido.",
    numericality: "El campo email no debe ser numérico.",
    customError: "El email ingresado no es válido.",
  },
  identificacion: {
    valueMissing: "El campo identificación no puede estar vacío.",
    typeMismatch: "Por favor, ingrese un número de identificación válido.",
    patternMismatch: "Por favor, ingrese un número de identificación válido.",
    rangeOverflow: "El valor es demasiado grande.",
    rangeUnderflow: "El valor es demasiado pequeño.",
    stepMismatch: "El valor no está en el paso correcto.",
    tooLong: "El número de identificación es demasiado largo.",
    tooShort: "El campo no tiene caracteres suficientes.",
    url: "El campo identificación no debe ser una URL.",
    email: "El campo identificación no debe ser un correo electrónico.",
    numericality: "El campo identificación debe ser numérico.",
    customError: "El número de identificación ingresado no es válido.",
  },
  cuil: {
    valueMissing: "El campo cuil/cuit no puede estar vacío.",
    typeMismatch: "Por favor, ingrese un cuil/cuit válido.",
    patternMismatch: "Por favor, ingrese un cuil/cuit válido.",
    rangeOverflow: "El valor es demasiado grande.",
    rangeUnderflow: "El valor es demasiado pequeño.",
    stepMismatch: "El valor no está en el paso correcto.",
    tooLong: "El cuil/cuit es demasiado largo.",
    tooShort: "El campo no tiene caracteres suficientes.",
    url: "El campo cuil/cuit no debe ser una URL.",
    email: "El campo cuil/cuit no debe ser un correo electrónico.",
    numericality: "El campo cuil/cuit debe ser numérico.",
    customError: "El cuil/cuit ingresado no existe.",
  },
  fecha_nacimiento: {
    valueMissing: "El campo fecha nacimiento no puede estar vacío.",
    typeMismatch: "Por favor, ingrese una fecha de nacimiento válida.",
    patternMismatch: "Por favor, ingrese una fecha de nacimiento válida.",
    rangeOverflow: "El valor es demasiado grande.",
    rangeUnderflow: "El valor es demasiado pequeño.",
    stepMismatch: "El valor no está en el paso correcto.",
    tooLong: "La fecha de nacimiento es demasiado larga.",
    tooShort: "El campo no tiene caracteres suficientes.",
    url: "El campo fecha de nacimiento no debe ser una URL.",
    email: "El campo fecha de nacimiento no debe ser un correo electrónico.",
    numericality: "El campo fecha de nacimiento no debe ser numérico.",
    customError: "Debes ser mayor de 18 años para registrarte.",
  },
  terminos: {
    valueMissing: "Debes aceptar los términos antes de continuar.",
    typeMismatch: "El campo términos no debe ser un tipo inválido.",
    patternMismatch: "El campo términos no coincide con el patrón requerido.",
    rangeOverflow: "El valor es demasiado grande.",
    rangeUnderflow: "El valor es demasiado pequeño.",
    stepMismatch: "El valor no está en el paso correcto.",
    tooLong: "El campo términos es demasiado largo.",
    tooShort: "El campo términos es demasiado corto.",
    url: "El campo términos no debe ser una URL.",
    email: "El campo términos no debe ser un correo electrónico.",
    numericality: "El campo términos no debe ser numérico.",
    customError: "Debes aceptar los términos antes de continuar.",
  },
};
